***************
*** 19,24 ****
  obj-$(CONFIG_USB_U132_HCD)	+= host/
  obj-$(CONFIG_USB_R8A66597_HCD)	+= host/
  obj-$(CONFIG_USB_HWA_HCD)	+= host/
  
  obj-$(CONFIG_USB_C67X00_HCD)	+= c67x00/
  
--- 19,25 ----
  obj-$(CONFIG_USB_U132_HCD)	+= host/
  obj-$(CONFIG_USB_R8A66597_HCD)	+= host/
  obj-$(CONFIG_USB_HWA_HCD)	+= host/
+ obj-$(CONFIG_USB_ISP1362_HCD)	+= host/
  
  obj-$(CONFIG_USB_C67X00_HCD)	+= c67x00/
  
