# TMPA9xx Platform Support
snd-soc-tmpa9xx-objs := tmpa9xx-pcm.o
snd-soc-tmpa9xx-i2s-objs := tmpa9xx-i2s.o

obj-$(CONFIG_SND_SOC_TMPA9XX) += snd-soc-tmpa9xx.o
obj-$(CONFIG_SND_SOC_TMPA9XX_I2S) += snd-soc-tmpa9xx-i2s.o

# machine support
snd-soc-topas-objs := baseboard-topas910.o
snd-soc-glynbb-objs := baseboard-glynbb.o

obj-$(CONFIG_SND_SOC_TMPA9XX_TOPAS) += snd-soc-topas.o
obj-$(CONFIG_SND_SOC_TMPA9XX_GLYNBB) += snd-soc-glynbb.o
